# Interface
verbose = "info"
no_progress = true
cache = true
max_cache_age = "10m"

# Stealth
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0"

# Prevent 'Too Many Open Files'
max_concurrency = 32

# Check links inside `<code>` and `<pre>` blocks and Markdown code blocks
include_verbatim = true

# Check fragments in links
include_fragments = true

# Don't check emails, it's problematic
include_mail = false

# Add 'Too many requests'
accept = ["100..=103", "200..=299", "429"]

# Be benevolent
max_retries = 5
timeout = 30

# Exclude
exclude = [
    # Specifications
    "^https://ogp\\.me/ns/website",

    # Infrastructure
    "^https://juniorguru\\.memberful\\.com",
    "^https://js\\.memberful\\.com",
    "^https://assets\\.memberful\\.com",
    "^https://js\\.stripe\\.com",
    "^https://m\\.stripe\\.network",

    # Anti-scraping protections
    "^https://www\\.linkedin\\.com",

    # Read the Docs anti-scraping protections
    "^https://docs\\.pyvec\\.org",
    "^https://www\\.writethedocs\\.org",

    # Expiring jobs
    "^https://jobs\\.cz/fp/",
    "^https://jobs\\.cz/rpd/",

    # Mysterious Cloudinary 404s for club avatars
    "https://res\\.cloudinary\\.com/juniorguru/image/fetch/[^/]+/https://junior\\.guru/static/avatars-club/[^\\.]+\\.png"
]
