# Interface
verbose = "info"
no_progress = true
cache = true
max_cache_age = "10m"

# Stealth
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:128.0) Gecko/20100101 Firefox/128.0"

# Prevent 'Too Many Open Files'
max_concurrency = 32

# Check links inside `<code>` and `<pre>` blocks and Markdown code blocks
include_verbatim = true

# Check fragments in links
include_fragments = true

# Don't check emails, it's problematic
include_mail = false

# Add 'Too many requests'
accept = ["100..=103", "200..=299", "429"]

# Be benevolent
max_retries = 5
timeout = 30

# Exclude
exclude = [
    # Specifications
    "https://ogp.me/ns/website",

    # Infrastructure
    "juniorguru.memberful.com",
    "js.memberful.com",
    "assets.memberful.com",
    "js.stripe.com",
    "m.stripe.network",

    # Anti-scraping protections
    "glassdoor.com",
    "upwork.com",
    "toptal.com",
    "make.com",
    "udemy.com",
    "datacamp.com",
    "europass.cz",
    "support.discord.com",
    "keyguru.cz",
    "robime.it",
    "reddit.com",
    "ulekare.cz",
    "epravo.cz",
    "linkedin.com",
    "podnikatel.cz",
    "root.cz",
    "akamai.com",
    "udacity.com",
    "hearthis.at",
    "freecodecamp.org",
    "techinterviewhandbook.org",

    # Read the Docs anti-scraping protections
    "docs.pyvec.org",
    "writethedocs.org",

    # Expiring jobs
    "jobs.cz/fp/",
    "jobs.cz/rpd/",
]
